---
- hosts: dev
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker module for Python 3
      pip:
        name: docker
        executable: pip3
        state: present

    - name: Start the container
      docker_container:
        name: dictionary
        image: "baimisaac/dictionary:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - "8080:8080"
